version: "3"
services:
  monolog-elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
    environment:
      - node.name=monolog-elasticsearch
      - cluster.name=es-docker-cluster
      - discovery.type=single-node
    ports:
      - 9200:9200
