version: "3"
services:
  monolog-elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.16.1
    environment:
      - node.name=monolog-elasticsearch
      - cluster.name=es-docker-cluster
      - discovery.type=single-node
    ports:
      - 9200:9200
  kibana:
    container_name: monolog-kibana
    image: docker.elastic.co/kibana/kibana:8.13.4
    environment:
      - ELASTICSEARCH_HOSTS=http://monolog-elasticsearch:9200
    ports:
      - 5601:5601
