version: "3"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    volumes:
      - elastic_data:/usr/share/elasticsearch/data
    environment:
      - ES_JAVA_OPTS=-Xmx4g
      - cluster.name=code-du-travail-data-elasticsearch
      - node.name=code-du-travail-data-elasticsearch-single-node
      - network.host=0.0.0.0
      - discovery.type=single-node
      - http.cors.enabled=true
      - http.cors.allow-origin='*'
      - xpack.security.enabled=false
      - xpack.ml.enabled=false
      - xpack.graph.enabled=false
      - xpack.watcher.enabled=false
    ports:
      - 9200:9200

  kibana:
    image: docker.elastic.co/kibana/kibana:8.13.4
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch

volumes:
  elastic_data:
