export const removeArr = new Set([
  "Santé, sécurité et conditions de travail",
  "Santé au travail",
  "Départ de l'entreprise",
  "Autres départs",
  "Emploi et formation professionnelle",
  "Formation professionnelle",
  "Emploi et formation professionnelle",
  "Entreprises en difficulté",
  "Temps de travail",
  "Congés et repos",
  "Congés",
  "Départ de l'entreprise",
  "Salaire et Rémunération",
  "Embauche et contrat de travail",
  "Contrat de travail",
  "Embauche et contrat de travail",
  "Contrat de travail",
  "Congés et repos",
  "Emploi et formation professionnelle",
  "Emploi",
  "Emploi et formation professionnelle",
  "Formation professionnelle",
  "Santé, sécurité et conditions de travail",
  "Risques professionnels et prévention",
  "Santé, sécurité et conditions de travail",
  "Congés et repos",
  "Emploi et formation professionnelle",
  "Formation professionnelle",
  "Congés et repos",
  "Congés",
  "Congés et repos",
  "Congés",
  "Congés et repos",
  "Congés",
  "Embauche et contrat de travail",
  "Contrat de travail",
  "Embauche et contrat de travail",
  "Contrat de travail",
  "Embauche et contrat de travail",
  "Embauche et contrat de travail",
  "Contrat de travail",
  "Embauche et contrat de travail",
  "Contrat de travail",
  "Temps de travail",
  "Durée du travail",
  "Emploi et formation professionnelle",
  "Emploi",
  "Départ de l'entreprise",
  "Départ de l'entreprise",
  "Retraite",
  "Embauche et contrat de travail",
  "Embauche",
  "Congés et repos",
  "Emploi et formation professionnelle",
  "Formation professionnelle",
  "Départ de l'entreprise",
  "Santé, sécurité et conditions de travail",
  "Conditions de travail",
  "Temps de travail",
  "Temps de travail",
  "Durée du travail",
  "Temps de travail",
  "Durée du travail",
  "Santé, sécurité et conditions de travail",
  "Conditions de travail",
  "Embauche et contrat de travail",
  "Emploi et formation professionnelle",
  "Emploi et formation professionnelle",
  "Salaire et Rémunération",
  "Santé, sécurité et conditions de travail",
  "Conditions de travail",
  "Santé, sécurité et conditions de travail",
  "Travailleurs et secteurs spécifiques",
  "Départ de l'entreprise",
  "Embauche et contrat de travail",
  "Embauche",
  "Emploi et formation professionnelle",
  "Conflits au travail et contrôle de la réglementation",
  "Embauche et contrat de travail",
  "Embauche",
  "Santé, sécurité et conditions de travail",
  "Travailleurs et secteurs spécifiques",
  "Santé, sécurité et conditions de travail",
  "Conditions de travail",
  "Temps de travail",
  "Santé, sécurité et conditions de travail",
  "Santé au travail",
  "Conflits au travail et contrôle de la réglementation",
  "Salaire et Rémunération",
  "Épargne salariale",
  "Embauche et contrat de travail",
  "Contrat de travail",
  "Embauche et contrat de travail",
  "Embauche",
  "Santé, sécurité et conditions de travail",
  "Travailleurs et secteurs spécifiques",
  "Emploi et formation professionnelle",
  "Emploi",
  "Emploi et formation professionnelle",
  "Formation professionnelle",
  "Conflits au travail et contrôle de la réglementation",
  "Emploi et formation professionnelle",
  "Emploi",
  "Emploi et formation professionnelle",
  "Emploi",
  "Représentation du personnel et négociation collective",
  "Santé, sécurité et conditions de travail",
  "Conditions de travail",
  "Départ de l'entreprise",
  "Départ de l'entreprise",
  "Licenciement",
  "Départ de l'entreprise",
  "Licenciement",
  "Départ de l'entreprise",
  "Licenciement",
  "Santé, sécurité et conditions de travail",
  "Conditions de travail",
  "Santé, sécurité et conditions de travail",
  "Santé au travail",
  "Embauche et contrat de travail",
  "Embauche",
  "Départ de l'entreprise",
  "Retraite",
  "Embauche et contrat de travail",
  "Contrat de travail",
  "Représentation du personnel et négociation collective",
  "Représentation du personnel et négociation collective",
  "Santé, sécurité et conditions de travail",
  "Risques professionnels et prévention",
  "Congés et repos",
  "Repos",
  "Embauche et contrat de travail",
  "Embauche",
  "Salaire et Rémunération",
  "Épargne salariale",
  "Emploi et formation professionnelle",
  "Emploi",
  "Départ de l'entreprise",
  "Retraite",
  "Salaire et Rémunération",
  "Départ de l'entreprise",
  "Autres départs",
  "Emploi et formation professionnelle",
  "Formation professionnelle",
  "Congés et repos",
  "Santé, sécurité et conditions de travail",
  "Conditions de travail",
  "Salaire et Rémunération",
  "Congés et repos",
  "Congés et repos",
  "Repos",
  "Représentation du personnel et négociation collective",
  "Départ de l'entreprise",
  "Santé, sécurité et conditions de travail",
  "Risques professionnels et prévention",
  "Santé, sécurité et conditions de travail",
  "Départ de l'entreprise",
  "Départ de l'entreprise",
  "Rupture conventionnelle",
  "Départ de l'entreprise",
  "Rupture conventionnelle",
  "Salaire et Rémunération",
  "Conflits au travail et contrôle de la réglementation",
  "Santé, sécurité et conditions de travail",
  "Emploi et formation professionnelle",
  "Emploi",
  "Embauche et contrat de travail",
  "Embauche",
  "Santé, sécurité et conditions de travail",
  "Santé au travail",
  "Santé, sécurité et conditions de travail",
  "Conditions de travail",
  "Temps de travail",
  "Temps de travail",
  "Conflits au travail et contrôle de la réglementation",
  "Santé, sécurité et conditions de travail",
  "Travailleurs et secteurs spécifiques",
  "Santé, sécurité et conditions de travail",
  "Travailleurs et secteurs spécifiques",
  "Embauche et contrat de travail",
  "Embauche",
  "Santé, sécurité et conditions de travail",
  "Emploi et formation professionnelle",
  "Emploi",
  "Emploi et formation professionnelle",
  "Formation professionnelle",
]);
