export const removeArr = new Set([
  "Accident du travail et maladie professionnelle",
  "Accord de performance collective",
  "Acteurs de la formation",
  "Activité partielle (anciennement chômage partiel)",
  "Aménagement du temps de travail",
  "Autres congés",
  "Autres départs",
  "Bulletin de salaire et cotisations sociales",
  "CDD",
  "CDI",
  "Compte personnel d'activité (CPA)",
  "Compte personnel de formation (CPF)",
  "Compte professionnel de prévention (C2P)",
  "Compte épargne-temps (CET)",
  "Conditions de travail",
  "Conflits au travail et contrôle de la réglementation",
  "Congés",
  "Congés et absences pour formation",
  "Congés et repos",
  "Congés liés à la naissance et à l'enfance",
  "Congés payés",
  "Congés pour événément familial",
  "Contrat d'apprentissage",
  "Contrat de professionnalisation",
  "Contrat de travail",
  "Contrats d'insertion et emplois aidés",
  "Contrats divers et professions particulières",
  "Convention de forfait (en heures ou en jours)",
  "Demandeurs d'emploi",
  "Dimanches, jours fériés et ponts",
  "Dispositifs d'accès à la formation",
  "Documents à remettre au salarié",
  "Droit d'alerte et de retrait des salariés",
  "Durée du travail",
  "Durée du travail d'un jeune avant 18 ans",
  "Durée du travail à temps complet",
  "Démission",
  "Départ de l'entreprise",
  "Départ volontaire à la retraite",
  "Détachement",
  "Egalité professionnelle",
  "Embauche",
  "Embauche et contrat de travail",
  "Emploi",
  "Emploi et formation professionnelle",
  "Entreprises en difficulté",
  "Equipements de travail et de protection",
  "Femme enceinte - Maternité",
  "Fin d'un CDD - CTT",
  "Formalités d'embauche",
  "Formation professionnelle",
  "Grève",
  "Handicap",
  "Harcèlement et discrimination",
  "Heures supplémentaires, d'équivalence et astreintes",
  "Inaptitude",
  "Inspection du travail",
  "Intéressement et participation",
  "Intérim",
  "Jeunes",
  "Jeunes travailleurs",
  "La certification professionnelle",
  "Le conseil de prud'hommes",
  "Les aides à l'emploi",
  "Les structures d'insertion",
  "Les syndicats dans l'entreprise",
  "Libertés du salarié",
  "Licenciement",
  "Licenciement pour inaptitude",
  "Licenciement pour motif personnel",
  "Licenciement pour motif économique",
  "Lieu de travail",
  "Maladie",
  "Mise à la retraite",
  "Modification du contrat de travail",
  "Méthodes de recrutement",
  "Négociations dans l'entreprise",
  "Négociations de branche",
  "Obligations générales de prévention",
  "Pause",
  "Plans d'épargne salariale",
  "Politique de l'emploi",
  "Primes et avantages",
  "Prise d'acte et résiliation judiciaire",
  "Pré-retraite",
  "Publics et mesures spécifiques",
  "Période d'essai",
  "Remboursement des frais de transport",
  "Repos",
  "Repos quotidien et hebdomadaire",
  "Représentation du personnel",
  "Représentation du personnel et négociation collective",
  "Retraite",
  "Risques professionnels",
  "Risques professionnels et prévention",
  "Rupture conventionnelle",
  "Rupture conventionnelle collective",
  "Rupture conventionnelle individuelle",
  "Règlement intérieur d'une entreprise",
  "Réduction du temps de travail (RTT)",
  "Salaire",
  "Salaire et Rémunération",
  "Sanctions disciplinaires",
  "Santé au travail",
  "Santé, sécurité et conditions de travail",
  "Seniors",
  "Stage",
  "Suivi médical des salariés",
  "Temps de travail",
  "Temps partiel",
  "Travail de nuit et en soirée",
  "Travail illégal",
  "Travailleur de nuit",
  "Travailleur à domicile",
  "Travailleurs et secteurs spécifiques",
  "Travailleurs handicapés",
  "Travailleurs étrangers",
  "Télétravail",
  "Validation des acquis de l'expérience (VAE)",
  "Épargne salariale",
]);
