---
apiVersion: "bitnami.com/v1alpha1"
kind: "SealedSecret"
metadata:
  annotations: &a1
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: monolog
spec:
  encryptedData:
    ELASTICSEARCH_URL: AgAqjrHe62lDMlC8JHIi80G3nj/o8THIeBWpAtIs3OJscNWPxNjeEW7bnaSugSblTdcxGUT/zcYkT0rUzBaXc6iG/Pf6iZosIDk1iSENcDTSIkMhzWf+W8u3iz4vl+1QnYWN1Qpz1a5xkb6cuR106S+Sph9iZ8izELJs7+fe2J2hn7FTTVp2dVURS2kxiOACgMujGbJUnWLGtxYqe0Ugl91+3FvDE88r6RAjj9jk99pbiq7ppPnJNTKUqksaSyZgklGMLIk/T2LFTmNnF3eHOsrJDP/t10mntR9EuqVC2XNOTCKMhbkR3bW4Ul1aqDvPJd2o3O3QUgRezAFUuS2Q7zVm7xMbXDkUlijYm9iNrmP3QWzjILlY4KAx+8zns1aCapiNnPpn6+bPsxshHU3tu3Xs2hQJNvSOSIH6aGnibG8zy7WYTA+T8h6pB0g/ye51S51KUk1nONLp1C0w378srvJGP/MLqt+kuRlU6nS5CwvHGpnXj492BI7jjrgUWCDXzB2mjI06RQdEoAFEj+Re4DrsJJbzBreej61ZeK2oxSSXV/5XgEDdA2F36XZVQMtakygii0GAi8UIuiZtefzrA9Nv28WM2tKKCGGIGT8Gj/S/osPsh5TaBWJnqUsWGLwqzJjSfA2Ut/VwGfgGLBz49NDDeVO6EMIvj5thupLHVQcgOCbfbLbfFAKTOiYgo4NGteUhdM+7PgZs5Iy22uIJGfmYXfWLN7RFnKPgkwLDm2EU9bSNoG99W5JoLbjIVb4TPAoDIX5Fkd06T73L+HPHMqnNH9JQd/N/SEsD+ZiJPu0+1Q==
    API_KEY: AgDMFKmIig/sX8DHLBqLD4rQAovzmM5CvNTD21yAUvQziSTJgiyKc/3JXDMpelmGZZkqRsEI1M24kr/IoQVLBQSpi8mhq5ib6di6nvX8LNqE3EEPqSUzSDMOlQt5rzcUhJRweQqzgnBNtNPx+Ti+Ojb0/3fE6fVRRS6dvbzXA+aSL0p1BLxg/OsF1c3UgOY1NWS/xBG5aBYxekcpVis60Vt4xCCgK+OFevDeCATAGfs303EHKLb6wHBdRYvvS+5kTEU063I1cSryvqY5cq2AyegMyleyGMo44X75mUZMFBE2SqMfyDTFeyLk6StjFweHNDaOf7NSezicvT+anY1Cw+fQBshy8z+95OvWGtL6p6HNacnSul2e+Uym8PhZJotKhlvoH7xCrthTFREBKtikDNlEJdPj5Fz3BvjYFcxFK/8oqHoachnnFx/kFGJRo6QiUiXS4pdlGGsCUGWeJ6owQLUGPqaBVYtzjRfVw5H7mcszuTW6deiYogT1/n3mFfSkpCn7FojlPDel5hSdfl8wDg0c8mpbkxht4Tmiip5neCUAc2u1DobGi6JSl8wfEdqlYXEGb5Lr8+I22PTlTTtmBjHKgPqQndCdhDB8o++Z0oPymNglDOl1Hfl5Bn1PzVHNDR0XBCMuFI88C37BYUkHQT5U0us1sALtckiBjzmjVYhN/y21s0DdAeeHP/89eqv0Zcqdvs/Jq7SCDR9rEZIw4cSWcxi0nhJpWZyKq1khHwN0VaFnhT3Qu9lqcnF4aW8INrLsFPNqYDwR1ZUpo+o=
  template:
    metadata:
      annotations: *a1
      name: monolog
    type: "Opaque"
