name: Node.js CI

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * */3 *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: yarn
      - run: yarn --frozen-lockfile
      - run: ELASTICSEARCH_URL=${ELASTICSEARCH_URL} API_KEY=${API_KEY} yarn monolog retrieve -o data.csv
        env:
          ELASTICSEARCH_URL: ${{ secrets.ELASTIC_URL }}
          API_KEY: ${{ secrets.ELASTIC_API_KEY }}
      - run: ELASTICSEARCH_URL=${ELASTICSEARCH_URL} API_KEY=${API_KEY} yarn monolog covisits -d data-data.csv
        env:
            ELASTICSEARCH_URL: ${{ secrets.ELASTIC_URL }}
            API_KEY: ${{ secrets.ELASTIC_API_KEY }}
