name: Schedule

on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * *"

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 20.19.3
          cache: "yarn"
      - name: Retrieve data
        run: "./scripts/dump_matomo_yesterday.sh"
      - name: Ingest
        run: |
          yarn
          yarn monolog ingest
        env:
          CDTN_API_URL: https://code-du-travail-numerique-dev.dev.fabrique.social.gouv.fr
          ELASTICSEARCH_URL: ${{ secrets.ELASTICSEARCH_URL }}
          API_KEY: ${{ secrets.API_KEY }}
      - uses: mattermost/action-mattermost-notify@master
        if: failure()
        with:
          MATTERMOST_WEBHOOK_URL: ${{ secrets.MATTERMOST_WEBHOOK_URL }}
          PAYLOAD: |
            La récupération des données pour monolog a échoué.
            [Les logs sont disponibles ici](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})
